import type { PortfolioProject } from '../types'

// Reliable placeholder images (Picsum Photos – same seed = same image every time)
const image = (seed: string, w = 1200, h = 800) =>
  `https://picsum.photos/seed/${seed}/${w}/${h}`

export const portfolioProjects: PortfolioProject[] = [
  {
    id: 'movieshaker',
    title: 'MovieShaker.com',
    type: 'Video Processing Platform',
    category: 'Video',
    planningDays: 5,
    buildHours: 2,
    image: image('movieshaker-video'),
    challenge: 'Enterprise-grade video processing with ffmpeg',
    solution: 'React frontend, Node.js backend, Docker containers, PostgreSQL',
    results: [
      'Production-ready video processing',
      'User upload and library management',
      'Currently being rebuilt with SuperTokens',
    ],
    techStack: ['React', 'TypeScript', 'ffmpeg', 'Docker', 'PostgreSQL', 'S3'],
    tags: ['Video', 'ffmpeg', 'Full-Stack'],
    liveUrl: 'https://movieshaker.com',
    linkLabel: 'View Live',
    secondaryLink: '#',
    secondaryLabel: 'Currently Rebuilding',
  },
  {
    id: 'reelinvesting',
    title: 'reelInvesting.com',
    type: 'FinTech Platform',
    category: 'FinTech',
    planningDays: 4,
    buildHours: 3,
    image: image('reelinvesting-fintech'),
    challenge: 'Real-time financial tracking for investors',
    solution: 'React SPA with secure API, PostgreSQL database',
    results: [
      'Secure financial data handling',
      'Real-time investment tracking',
      'Live and operational',
    ],
    techStack: ['React', 'TypeScript', 'PostgreSQL', 'REST APIs'],
    tags: ['FinTech', 'Analytics', 'Security'],
    liveUrl: 'https://reelinvesting.com',
    linkLabel: 'View Live',
  },
  {
    id: 'afilminabox',
    title: 'aFilmInaBox.com',
    type: 'Media Delivery Platform',
    category: 'Media',
    planningDays: 3,
    buildHours: 1.5,
    image: image('afilminabox-media'),
    challenge: 'Scalable media content delivery',
    solution: 'React frontend with CDN integration',
    results: [
      'Fast content delivery',
      'Scalable architecture',
      'Production deployment',
    ],
    techStack: ['React', 'Docker', 'CDN', 'Node.js'],
    tags: ['Media', 'CDN', 'Streaming'],
    liveUrl: 'https://afilminabox.com',
    linkLabel: 'View Live',
  },
  {
    id: 'ffmpeg-api',
    title: 'ffmpeg API Controller',
    type: 'Video Processing API',
    category: 'API',
    planningDays: 5,
    buildHours: 2,
    image: image('ffmpeg-api-code'),
    challenge: 'Programmatic video processing service',
    solution: 'RESTful API for ffmpeg operations',
    results: [
      'Scalable video processing',
      'Queue-based architecture',
      'Powers MovieShaker backend',
    ],
    techStack: ['Node.js', 'Express', 'ffmpeg', 'Docker', 'Redis'],
    tags: ['API', 'Video', 'Backend'],
    linkLabel: 'Internal Service',
  },
  {
    id: 'ai-chatbot',
    title: 'AI Chatbot',
    type: 'AI-Powered Chatbot',
    category: 'AI',
    planningDays: 4,
    buildHours: 4,
    image: image('ai-chatbot-chat'),
    challenge: 'Intelligent customer service automation',
    solution: 'Claude API integration with custom training',
    results: [
      'Natural language processing',
      'Context-aware responses',
      'Production deployment',
    ],
    techStack: ['React', 'Node.js', 'Claude API', 'PostgreSQL'],
    tags: ['AI', 'Chat', 'Integration'],
    linkLabel: 'Private Client',
  },
  {
    id: 'ai-billing',
    title: 'AI Billing Passthrough',
    type: 'AI API Billing Handler',
    category: 'AI',
    planningDays: 3,
    buildHours: 3,
    image: image('ai-billing-dashboard'),
    challenge: 'Track and bill AI API usage accurately',
    solution: 'Passthrough handler with usage metering',
    results: [
      'Accurate usage tracking',
      'Automated billing',
      'Multi-tenant support',
    ],
    techStack: ['Node.js', 'PostgreSQL', 'Stripe', 'Redis'],
    tags: ['Billing', 'API', 'SaaS'],
    linkLabel: 'Internal Service',
  },
]
